name: Build and Package Extension

on:
    push:
        branches: [main]
    pull_request:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Install Nix
              uses: cachix/install-nix-action@v20
              with:
                  extra_nix_config: |
                      experimental-features = nix-command flakes

            # Cache Yarn dependencies here - RIGHT AFTER NIX INSTALL
            - name: Cache Yarn dependencies
              uses: actions/cache@v3
              id: yarn-cache
              with:
                  path: |
                      .yarn/cache
                      node_modules
                  key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-yarn-

            - name: Set up Nix environment
              run: |
                  nix develop --command yarn --version
                  nix develop --command vsce --version

            - name: Install dependencies
              run: |
                  nix develop --command yarn install --frozen-lockfile
                  # Only needed if using Yarn 2+ with PnP
                  nix develop --command yarn cache clean --mirror

            - name: Package extension
              run: |
                  nix develop --command vsce package --yarn -o vspieuvre.vsix

            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                  name: vspieuvre-extension
                  path: vspieuvre.vsix
